name: Pipeline

on: [push,workflow_dispatch]

jobs:
  build_default:
    uses: earnestdl/templates/.github/workflows/build.yml@main
    with: 
      id: default
      type: bash
      state: "variables.json"

  deploy_dev:
    needs: build_default
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: dev
      env: dev
      type: bash

  deploy_qa:
    needs: deploy_dev
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: qa
      env: qa
      type: bash

  deploy_stress:
    needs: deploy_qa
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: stress
      env: stress
      type: bash

  deploy_prod:
    needs: deploy_stress
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: prod
      env: prod
      type: bash
