name: Workflow

on: [push,workflow_dispatch]

jobs:
  build_default:
    name: Build default
    uses: earnestdl/templates/.github/workflows/build.yml@main
    with: 
      id: default
      type: bash
      state: "variables.json"

  deploy_dev:
    name: Deploy dev
    needs: build_default
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: dev
      env: dev
      type: bash

  deploy_qa:
    name: Deploy qa
    needs: deploy_dev
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: qa
      env: qa
      type: bash

  deploy_stress:
    name: Deploy stress
    needs: deploy_qa
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: stress
      env: stress
      type: bash

  deploy_prod:
    name: Deploy prod
    needs: deploy_stress
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      id: prod
      env: prod
      type: bash
